import SwiftUI

struct SettingsView: View {
    @AppStorage("themeMode") private var themeModeRaw = ThemeMode.light.rawValue
    @AppStorage("remindersEnabled") private var remindersEnabled = true
    @AppStorage("reminderHour") private var reminderHour = 19
    @AppStorage("cloudAnswersEnabled") private var cloudAnswersEnabled = true
    @Environment(\.dismiss) private var dismiss

    private let reminderHours = Array(6...23)
    private func hourLabel(_ h: Int) -> String {
        let suffix = h < 12 ? "AM" : "PM"
        let twelve = h % 12 == 0 ? 12 : h % 12
        return "\(twelve):00 \(suffix)"
    }

    private var mode: Binding<ThemeMode> {
        Binding(
            get: { ThemeMode(rawValue: themeModeRaw) ?? .system },
            set: { themeModeRaw = $0.rawValue }
        )
    }

    /// Live streak for the widget preview; falls back to a sample when there's no data yet.
    private var previewSnapshot: StreakSnapshot {
        let s = SharedStore.load()
        return s.lastActiveISO == nil ? .preview : s
    }

    // Where generated answers (Ask + Digest) actually run on THIS device.
    private var onDeviceAI: Bool { GenerationService().isAvailable }
    private var cloudConfigured: Bool { AppConfig.cloudGenerationURL != nil }
    /// The cloud opt-out only matters on a device without on-device AI.
    private var showsCloudToggle: Bool { !onDeviceAI && cloudConfigured }

    private var answersLabel: String {
        if onDeviceAI { return "On-device AI" }
        if cloudConfigured && cloudAnswersEnabled { return "Private cloud" }
        return "On-device (basic)"
    }

    private var privacyFooter: String {
        if onDeviceAI {
            return "Capture, search, and answers all run on your iPhone — your memories never leave your device."
        }
        if cloudConfigured && cloudAnswersEnabled {
            return "Capture, search, and storage run on your iPhone. This device doesn't support on-device AI, so Ask and your weekly Digest are generated by a private cloud service — only the few memories retrieved for each question are sent, never your full history. Turn this off to stay fully on-device."
        }
        return "Kairō runs entirely on your iPhone. Without on-device AI, Ask shows your most relevant memories instead of a written answer."
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Appearance") {
                    Picker("Theme", selection: mode) {
                        ForEach(ThemeMode.allCases) { m in
                            Label(m.label, systemImage: m.icon).tag(m)
                        }
                    }
                    .pickerStyle(.inline)
                }

                Section {
                    Toggle("Daily check-in reminder", isOn: $remindersEnabled)
                    if remindersEnabled {
                        Picker("Remind me at", selection: $reminderHour) {
                            ForEach(reminderHours, id: \.self) { Text(hourLabel($0)).tag($0) }
                        }
                    }
                } header: {
                    Text("Reminders")
                } footer: {
                    Text("If you haven't checked in, Kairo sends an evening nudge so your streak doesn't break. All on-device.")
                }
                .onChange(of: remindersEnabled) { _, on in
                    Task {
                        if on { await NotificationService.requestAuthorization() }
                        NotificationService.refresh()
                    }
                }
                .onChange(of: reminderHour) { _, _ in NotificationService.refresh() }

                Section {
                    VStack(alignment: .center, spacing: 14) {
                        StreakWidgetPreview(snapshot: previewSnapshot, medium: true)
                        StreakWidgetPreview(snapshot: previewSnapshot, medium: false)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 6)
                    .listRowBackground(Color.clear)
                } header: {
                    Text("Home-screen widget")
                } footer: {
                    Text("Meet Kairo the sun — add the widget from your home screen: long-press → ➕ → search “Kairō”. Kairo beams when you're on a streak and dozes off if you drift.")
                }

                Section {
                    if AppConfig.standalone {
                        LabeledContent("Storage", value: "On this iPhone")
                        LabeledContent("Answers", value: answersLabel)
                        if showsCloudToggle {
                            Toggle("Use private cloud for answers", isOn: $cloudAnswersEnabled)
                        }
                    } else {
                        LabeledContent("Backend", value: AppConfig.baseURL.absoluteString)
                    }
                    LabeledContent("Transcription",
                                   value: AppConfig.useOnDeviceTranscription ? "On-device" : "Server")
                    LabeledContent("Version", value: "0.2.0")
                } header: {
                    Text("About")
                } footer: {
                    if AppConfig.standalone {
                        Text(privacyFooter)
                    }
                }
            }
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }
}
